# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e0694bf544e61c1499de5695572327ccf150f9662f74100db46d85936672d1ed81bd38786c71ba0693ff6f5cffd7887a7f0b30d483b8273a2c99f2da83a4b498

test:
  secret_key_base: 78fa6ccba2463169067952073f16d6ecab6cedd1be2b35065aacf2a76b21defdd2154eaa9385e164cdeb9008c17a4d475c98071747186dce1c876e47c9afd0e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
